-- Seed Data Migration Script
-- This script migrates data from JSON mock database to PostgreSQL
-- Run this after applying the initial schema and RLS policies

-- Note: This is a reference SQL script showing the structure of INSERT statements
-- For actual migration, use the Python migration script: migrate_json_to_supabase.py

-- Example INSERT statements (these will be generated by the Python script):

-- INSERT INTO owners (id, name, email, phone, created_at, updated_at) VALUES
-- ('uuid-1', 'John Owner', 'owner@example.com', '+1-555-3333', NOW(), NOW());

-- INSERT INTO property_managers (id, name, email, phone, created_at, updated_at) VALUES
-- ('uuid-2', 'John management', 'sarah@management.com', '+1-555-2222', NOW(), NOW());

-- INSERT INTO properties (id, name, address, year_built, property_type, unit_count, owner_id, manager_id, representative_type, representative_id, created_at, updated_at) VALUES
-- ('uuid-3', 'Sunset Apartments', '123 Main St, Berlin, 10115, Germany', 1998, 'apartment_building', 24, 'uuid-1', 'uuid-2', 'property_manager', 'uuid-2', NOW(), NOW());

-- INSERT INTO owner_properties (owner_id, property_id) VALUES
-- ('uuid-1', 'uuid-3');

-- INSERT INTO manager_properties (manager_id, property_id) VALUES
-- ('uuid-2', 'uuid-3');

-- INSERT INTO tenants (id, name, email, phone, address, unit, property_id, created_at, updated_at) VALUES
-- ('uuid-4', 'John Tenant', 'john@example.com', '+1-555-1234', '123 Main St Apt 4B', '4B', 'uuid-3', NOW(), NOW());

-- INSERT INTO vendors (id, name, email, phone, emergency_available, created_at, updated_at) VALUES
-- ('uuid-5', 'QuickFix Locksmith', 'dispatch@quickfix.com', '+1-555-4444', true, NOW(), NOW());

-- INSERT INTO vendor_services (vendor_id, service_name) VALUES
-- ('uuid-5', 'locksmith');

-- INSERT INTO requests (id, requester_id, property_id, vendor_id, type, description, status, urgency, escalated, sentiment, confidence, notification_pending, summary, created_at, updated_at) VALUES
-- ('uuid-6', 'uuid-4', 'uuid-3', NULL, 'access_control', 'Conversation started', 'in_progress', 'medium', false, 'neutral', 0.9, false, 'The tenant has reported losing the key...', NOW(), NOW());

-- INSERT INTO conversation_messages (id, request_id, role, message, timestamp) VALUES
-- ('uuid-7', 'uuid-6', 'ai', 'Hello John Tenant, welcome to Ranting Chant...', NOW());

-- INSERT INTO notifications (id, request_id, type, recipient, recipient_type, status, timestamp) VALUES
-- ('uuid-8', 'uuid-6', 'email', 'sarah@management.com', 'manager', 'sent', NOW());
